version: "3.9"

services:
  minecraft:
    build:
      args:
        JAVA_VERSION: ${JAVA_VERSION}     #Select Java version
        LINK: ${LINK}                     #Download server.jar from link
        TYPE: ${TYPE}                     #Select server type: vanilla or papermc
        VERSION: ${VERSION}               #Select version e.g. 1.19.2
    restart: unless-stopped
    container_name: "mcserver"
    environment:
      UID: ${UID}                         #Specify the UID of user inside container
      MINMEMORY: ${MINMEMORY}             #Specify initial memory (-Xmx)    
      MAXMEMORY: ${MAXMEMORY}             #Specify maximum memory (-Xms)       
    volumes:
      - "./server:/server"                #Specify directory where all "server" files are located
    ports:
      - "${PORT}:25565"                   #Specify server port
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true