version: "3.9"

services:
  minecraft:
    build:
      args:                                                   #USE .env FILE
        JAVA_VERSION: ${JAVA_VERSION:-17-focal}           #Select Java version
    deploy:
      resources:
        limits:
          cpus: '${MAXCPU:-ALL}'
        reservations:
          cpus: '${MINCPU:-ALL}'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: ${SERVER_NAME:-mcserver}
    environment:
      TYPE: ${TYPE:-file}                                #Select server type: vanilla or papermc
      LINK: ${LINK:-}
      UID: ${UID:-1000}                                       #Specify the UID of user inside container
      GID: ${GID:-1000}                                       #Specify the GID of user inside container
      MINMEMORY: ${MINMEMORY:-1G}                             #Specify initial memory (-Xmx)    
      MAXMEMORY: ${MAXMEMORY:-2G}                             #Specify maximum memory (-Xms)
    volumes:
      - "${VOLUME_PATH:-./server}:/server"                    #Specify directory where all "server" files are located
    ports:
      - "${PORT:-25565}:25565"                                #Specify server port
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true